#!/bin/bash
# Connect to your EC2 instance:
ssh -i your-key-pair.pem ec2-user@your-ec2-instance-ip
sudo yum update -y
sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

#logstash-repo
sudo tee /etc/yum.repos.d/logstash.repo <<EOF
[logstash]
name=Elastic repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
EOF

#logstash-install
sudo yum install logstash -y
sudo service logstash start
sudo chkconfig --add logstash
sudo netstat -na | grep 9600
sudo mkdir /opt/farooq
sudo mkdir /opt/farooq/config
sudo mkdir /opt/farooq/pipeline
sudo rm -rf /opt/farooq/logstash/pipelines.yml
sudo cp -r /etc/logstash/*    /opt/farooq/config/

sudo rm -rf /opt/farooq/config/startup.options
sudo rm -rf /opt/farooq/config/logstash-sample.conf
sudo rm -rf /opt/farooq/config/conf.d

sudo tee /opt/farooq/config/pipelines.yml <<EOF
   - pipeline.id: farooq
     pipeline.workers: 2
     pipeline.batch.size: 300
     pipeline.batch.delay: 50
     path.config: "/opt/farooq/pipeline/*.conf"
EOF

sudo tee /opt/farooq/pipeline/logstashpluggin.conf  <<EOF
input { tcp { port => 12000 } }
filter { 
json { source => "message" } 
  mutate {
    add_field => {
      "Organization-Name" => "[BSN-TECH][TECHSOLUTIONS]"
      "Organization-Founder" => "[BABA][FAROOQ][SN]"
      "ORG-ID" => "SND-9154-001"
      "ORG-Location" => "[AMARAVATHI][AP-STATE]"
      "Contact-Number" => "[91766********]"
    }
    rename => { "message" => "Raw-Message" }
    remove_field => ["_jsonparsefailure"]
  }
}
output { stdout { codec => rubydebug } }

EOF

#Create a Logstash service file:
sudo tee /etc/systemd/system/babafarooq.service <<EOF
[Unit]
Description=logstash
After=network.target

[Service]
#User=farooq
Type=simple
WorkingDirectory=/opt/farooq
User=logstash
Group=logstash

EnvironmentFile=-/etc/default/logstash
EnvironmentFile=-/etc/sysconfig/logstash
ExecStart=/usr/share/logstash/bin/logstash "--path.settings" "/opt/farooq/config"
RemainAfterExit=yes
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target

EOF

sudo systemctl daemon-reload
sudo systemctl start babafarooq
sudo systemctl enable babafarooq

# sudo journalctl -u babafarooq
# Install firewalld
sudo yum install -y firewalld
sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --zone=public --add-port=12000-14000/tcp --permanent
sudo firewall-cmd --zone=public --add-port=12000-14000/udp --permanent
sudo firewall-cmd --reload
sudo firewall-cmd --list-ports
sudo yum install nc -y
sudo systemctl status babafarooq





