winlogbeat.event_logs:
  - name: Application
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Security
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: System
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: BluArmour
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Microsoft-Windows-Windows Defender/Operational
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Microsoft-windows-Sysmon/Operational
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Windows PowerShell
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Microsoft-Windows-WMI-Activity/Operational
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"
  - name: Microsoft-windows-TaskScheduler/Operational
    ignore_older: 15m
    fields:
      log: "windows-log"
      organization-id: "Snb-Tech-9141"
      organization-name: "Snb-Tech-Solutions"

output.logstash:
  hosts: ["logstash_ipadd:12102"]
  codec.json:
    pretty: true

winlogbeat.registry_file: C:/Program Files/winlogbeat/.winlogbeat.yml
