{
 "title": "Elasticsearch-updated",
 "description": "Elasticsearch detailed dashboard with instance picker",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(elasticsearch_process_cpu_percent,name)"
   },
   {
    "name": "instance",
    "query": "label_values(elasticsearch_cluster_health_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"ELK-CLUSTER\", color=\"green\"}) * 2 + max(elasticsearch_cluster_health_status{cluster=\"ELK-CLUSTER\", color=\"yellow\"}) * 1",
     "legendFormat": "Cluster Health"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster.*\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "active primary shards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "initializing shards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "relocating shards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "unassigned shards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=~\"$cluster.*\",es_master_node=\"true\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{ name }} - master"
    },
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=~\"$cluster.*\",es_data_node=\"true\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{ name }} - data"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=~\"$cluster.*\",name=~\"$node.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{ name }} - used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{cluster=~\"$cluster.*\",name=~\"$node.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{ name }} - committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=~\"$cluster.*\",name=~\"$node.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{ name }} - max: {{area}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{cluster=~\"$cluster.*\", instance=~\"$instance.*\"}/elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"})",
     "legendFormat": "{{ name }} - {{path}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} -sent"
    },
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} -received"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Documents count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_deleted{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total Operations rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - flush"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_ms_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_ms_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_ms_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_total_time_ms_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_time_ms_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{ name }} - flush"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Field data memory size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": " irate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster.*\",name=~\"$node.*\"}[$interval])",
     "legendFormat": "{{name}} - {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_queue_count{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{name}} - {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}",
     "legendFormat": "{{name}} - {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 18, "y": 64 },
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}} - {{ type }}"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster.*\",name=~\"$node.*\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  }
 ]
}